// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDetailTransaction = "detail_transaction"

// DetailTransaction mapped from table <detail_transaction>
type DetailTransaction struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID     int32   `gorm:"column:product_id;not null" json:"product_id"`
	Quantity      float64 `gorm:"column:quantity;not null" json:"quantity"`
	TransactionID int32   `gorm:"column:transaction_id;not null" json:"transaction_id"`
}

// TableName DetailTransaction's table name
func (*DetailTransaction) TableName() string {
	return TableNameDetailTransaction
}
