// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Item        string `gorm:"column:item" json:"item"`
	Description string `gorm:"column:description" json:"description"`
	Price       int64  `gorm:"column:price" json:"price"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
