// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSupply = "supply"

// Supply mapped from table <supply>
type Supply struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Unit string `gorm:"column:unit" json:"unit"`
}

// TableName Supply's table name
func (*Supply) TableName() string {
	return TableNameSupply
}
