// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID                  int32               `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Branchname          string              `gorm:"column:branchname" json:"branchname"`
	Timestamp           time.Time           `gorm:"column:timestamp;default:now()" json:"timestamp"`
	Totalprice          int64               `gorm:"column:totalprice" json:"totalprice"`
	Isreturningcustomer *bool               `gorm:"column:isreturningcustomer" json:"isreturningcustomer"`
	Isdelete            time.Time           `gorm:"column:isdelete" json:"isdelete"`
	Imagepath           string              `gorm:"column:imagepath" json:"imagepath"`
	Createdby           int32               `gorm:"column:createdby;not null" json:"createdby"`
	Updatedby           int32               `gorm:"column:updatedby" json:"updatedby"`
	Updatedat           time.Time           `gorm:"column:updatedat" json:"updatedat"`
	Customername        string              `gorm:"column:customername" json:"customername"`
	DetailTransaction   []DetailTransaction `gorm:"foreignKey:transaction_id" json:"detail_transaction"`
	CreatedByUser       User                `gorm:"foreignKey:createdby" json:"created_by_user"`
	UpdatedByUser       User                `gorm:"foreignKey:updatedby" json:"updated_by_user"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
