// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID                  int32               `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Branchname          string              `gorm:"column:branchname" json:"branchname"`
	Timestamp           time.Time           `gorm:"column:timestamp;default:now()" json:"timestamp"`
	Totalprice          int64               `gorm:"column:totalprice" json:"totalprice"`
	Isreturningcustomer *bool               `gorm:"column:isreturningcustomer" json:"isreturningcustomer"`
	DetailTransaction   []DetailTransaction `gorm:"foreignKey:transaction_id" json:"detail_transaction"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
