// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	DetailTransaction *detailTransaction
	Product           *product
	Supply            *supply
	Transaction       *transaction
	User              *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	DetailTransaction = &Q.DetailTransaction
	Product = &Q.Product
	Supply = &Q.Supply
	Transaction = &Q.Transaction
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		DetailTransaction: newDetailTransaction(db, opts...),
		Product:           newProduct(db, opts...),
		Supply:            newSupply(db, opts...),
		Transaction:       newTransaction(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	DetailTransaction detailTransaction
	Product           product
	Supply            supply
	Transaction       transaction
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		DetailTransaction: q.DetailTransaction.clone(db),
		Product:           q.Product.clone(db),
		Supply:            q.Supply.clone(db),
		Transaction:       q.Transaction.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		DetailTransaction: q.DetailTransaction.replaceDB(db),
		Product:           q.Product.replaceDB(db),
		Supply:            q.Supply.replaceDB(db),
		Transaction:       q.Transaction.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	DetailTransaction IDetailTransactionDo
	Product           IProductDo
	Supply            ISupplyDo
	Transaction       ITransactionDo
	User              IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		DetailTransaction: q.DetailTransaction.WithContext(ctx),
		Product:           q.Product.WithContext(ctx),
		Supply:            q.Supply.WithContext(ctx),
		Transaction:       q.Transaction.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
