// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"Lekris-BE/model"
)

func newSupply(db *gorm.DB, opts ...gen.DOOption) supply {
	_supply := supply{}

	_supply.supplyDo.UseDB(db, opts...)
	_supply.supplyDo.UseModel(&model.Supply{})

	tableName := _supply.supplyDo.TableName()
	_supply.ALL = field.NewAsterisk(tableName)
	_supply.ID = field.NewInt32(tableName, "id")
	_supply.Name = field.NewString(tableName, "name")
	_supply.Unit = field.NewString(tableName, "unit")

	_supply.fillFieldMap()

	return _supply
}

type supply struct {
	supplyDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String
	Unit field.String

	fieldMap map[string]field.Expr
}

func (s supply) Table(newTableName string) *supply {
	s.supplyDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s supply) As(alias string) *supply {
	s.supplyDo.DO = *(s.supplyDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *supply) updateTableName(table string) *supply {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Name = field.NewString(table, "name")
	s.Unit = field.NewString(table, "unit")

	s.fillFieldMap()

	return s
}

func (s *supply) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *supply) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["unit"] = s.Unit
}

func (s supply) clone(db *gorm.DB) supply {
	s.supplyDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s supply) replaceDB(db *gorm.DB) supply {
	s.supplyDo.ReplaceDB(db)
	return s
}

type supplyDo struct{ gen.DO }

type ISupplyDo interface {
	gen.SubQuery
	Debug() ISupplyDo
	WithContext(ctx context.Context) ISupplyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISupplyDo
	WriteDB() ISupplyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISupplyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISupplyDo
	Not(conds ...gen.Condition) ISupplyDo
	Or(conds ...gen.Condition) ISupplyDo
	Select(conds ...field.Expr) ISupplyDo
	Where(conds ...gen.Condition) ISupplyDo
	Order(conds ...field.Expr) ISupplyDo
	Distinct(cols ...field.Expr) ISupplyDo
	Omit(cols ...field.Expr) ISupplyDo
	Join(table schema.Tabler, on ...field.Expr) ISupplyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISupplyDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISupplyDo
	Group(cols ...field.Expr) ISupplyDo
	Having(conds ...gen.Condition) ISupplyDo
	Limit(limit int) ISupplyDo
	Offset(offset int) ISupplyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISupplyDo
	Unscoped() ISupplyDo
	Create(values ...*model.Supply) error
	CreateInBatches(values []*model.Supply, batchSize int) error
	Save(values ...*model.Supply) error
	First() (*model.Supply, error)
	Take() (*model.Supply, error)
	Last() (*model.Supply, error)
	Find() ([]*model.Supply, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Supply, err error)
	FindInBatches(result *[]*model.Supply, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Supply) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISupplyDo
	Assign(attrs ...field.AssignExpr) ISupplyDo
	Joins(fields ...field.RelationField) ISupplyDo
	Preload(fields ...field.RelationField) ISupplyDo
	FirstOrInit() (*model.Supply, error)
	FirstOrCreate() (*model.Supply, error)
	FindByPage(offset int, limit int) (result []*model.Supply, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISupplyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s supplyDo) Debug() ISupplyDo {
	return s.withDO(s.DO.Debug())
}

func (s supplyDo) WithContext(ctx context.Context) ISupplyDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s supplyDo) ReadDB() ISupplyDo {
	return s.Clauses(dbresolver.Read)
}

func (s supplyDo) WriteDB() ISupplyDo {
	return s.Clauses(dbresolver.Write)
}

func (s supplyDo) Session(config *gorm.Session) ISupplyDo {
	return s.withDO(s.DO.Session(config))
}

func (s supplyDo) Clauses(conds ...clause.Expression) ISupplyDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s supplyDo) Returning(value interface{}, columns ...string) ISupplyDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s supplyDo) Not(conds ...gen.Condition) ISupplyDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s supplyDo) Or(conds ...gen.Condition) ISupplyDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s supplyDo) Select(conds ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s supplyDo) Where(conds ...gen.Condition) ISupplyDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s supplyDo) Order(conds ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s supplyDo) Distinct(cols ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s supplyDo) Omit(cols ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s supplyDo) Join(table schema.Tabler, on ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s supplyDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s supplyDo) RightJoin(table schema.Tabler, on ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s supplyDo) Group(cols ...field.Expr) ISupplyDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s supplyDo) Having(conds ...gen.Condition) ISupplyDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s supplyDo) Limit(limit int) ISupplyDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s supplyDo) Offset(offset int) ISupplyDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s supplyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISupplyDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s supplyDo) Unscoped() ISupplyDo {
	return s.withDO(s.DO.Unscoped())
}

func (s supplyDo) Create(values ...*model.Supply) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s supplyDo) CreateInBatches(values []*model.Supply, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s supplyDo) Save(values ...*model.Supply) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s supplyDo) First() (*model.Supply, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Supply), nil
	}
}

func (s supplyDo) Take() (*model.Supply, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Supply), nil
	}
}

func (s supplyDo) Last() (*model.Supply, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Supply), nil
	}
}

func (s supplyDo) Find() ([]*model.Supply, error) {
	result, err := s.DO.Find()
	return result.([]*model.Supply), err
}

func (s supplyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Supply, err error) {
	buf := make([]*model.Supply, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s supplyDo) FindInBatches(result *[]*model.Supply, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s supplyDo) Attrs(attrs ...field.AssignExpr) ISupplyDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s supplyDo) Assign(attrs ...field.AssignExpr) ISupplyDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s supplyDo) Joins(fields ...field.RelationField) ISupplyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s supplyDo) Preload(fields ...field.RelationField) ISupplyDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s supplyDo) FirstOrInit() (*model.Supply, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Supply), nil
	}
}

func (s supplyDo) FirstOrCreate() (*model.Supply, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Supply), nil
	}
}

func (s supplyDo) FindByPage(offset int, limit int) (result []*model.Supply, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s supplyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s supplyDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s supplyDo) Delete(models ...*model.Supply) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *supplyDo) withDO(do gen.Dao) *supplyDo {
	s.DO = *do.(*gen.DO)
	return s
}
